repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.3
  hooks:
  - id: clang-format
    types: [c]
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
